"""Tests for report merging."""

import json
import tempfile
from pathlib import Path

from flake_review.report import merge_json_reports, merge_markdown_reports

DARWIN_REPORT = """\
# Flake Review Results for [#137](https://github.com/example/repo/pull/137)

**Available systems:** aarch64-darwin, x86_64-darwin
**Requested systems:** aarch64-darwin, x86_64-darwin

### 🔄 Modified (2)

- ✅ `packages.aarch64-darwin.injection`
  - Output: `/nix/store/abc-TidaLuna`
- ✅ `packages.x86_64-darwin.injection`
  - Output: `/nix/store/def-TidaLuna`

---
*Generated by [flake-review](https://github.com/ojsef39/flake-review)*"""

LINUX_REPORT = """\
# Flake Review Results for [#137](https://github.com/example/repo/pull/137)

**Available systems:** x86_64-linux
**Requested systems:** x86_64-linux

### 🔄 Modified (1)

- ✅ `packages.x86_64-linux.injection`
  - Output: `/nix/store/ghi-TidaLuna`

---
*Generated by [flake-review](https://github.com/ojsef39/flake-review)*"""


def _write_temp(content: str) -> str:
    """Write content to a temp file and return the path."""
    f = tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False)
    f.write(content)
    f.close()
    return f.name


def test_merge_two_reports() -> None:
    """Test merging two platform reports."""
    darwin_path = _write_temp(DARWIN_REPORT)
    linux_path = _write_temp(LINUX_REPORT)

    merged = merge_markdown_reports(
        [darwin_path, linux_path],
        title="Flake Review Results for #137",
    )

    # Has the custom title
    assert "# Flake Review Results for #137" in merged

    # Has content from both reports
    assert "packages.aarch64-darwin.injection" in merged
    assert "packages.x86_64-linux.injection" in merged

    # Has footer exactly once
    assert merged.count("Generated by [flake-review]") == 1

    # No duplicate titles
    lines = [line for line in merged.split("\n") if line.startswith("# ")]
    assert len(lines) == 1

    Path(darwin_path).unlink()
    Path(linux_path).unlink()


def test_merge_single_report() -> None:
    """Test merging a single report."""
    path = _write_temp(DARWIN_REPORT)

    merged = merge_markdown_reports([path], title="Test")

    assert "# Test" in merged
    assert "packages.aarch64-darwin.injection" in merged
    assert merged.count("Generated by [flake-review]") == 1

    Path(path).unlink()


def test_merge_preserves_system_info() -> None:
    """Test that system info from individual reports is preserved."""
    darwin_path = _write_temp(DARWIN_REPORT)
    linux_path = _write_temp(LINUX_REPORT)

    merged = merge_markdown_reports([darwin_path, linux_path])

    assert "aarch64-darwin" in merged
    assert "x86_64-linux" in merged

    Path(darwin_path).unlink()
    Path(linux_path).unlink()


DARWIN_JSON = {
    "version": 1,
    "metadata": {
        "requested_systems": ["aarch64-darwin", "x86_64-darwin"],
        "available_systems": [
            "aarch64-darwin",
            "aarch64-linux",
            "x86_64-darwin",
            "x86_64-linux",
        ],
    },
    "changes": {
        "added": [],
        "removed": [],
        "modified": [
            {
                "old": {
                    "attr_path": "packages.aarch64-darwin.pkg",
                    "drv_path": "/nix/store/old.drv",
                    "output_type": "packages",
                    "system": "aarch64-darwin",
                    "name": "pkg",
                },
                "new": {
                    "attr_path": "packages.aarch64-darwin.pkg",
                    "drv_path": "/nix/store/new.drv",
                    "output_type": "packages",
                    "system": "aarch64-darwin",
                    "name": "pkg",
                },
                "nix_diff": "- old\n+ new",
                "build": {
                    "success": True,
                    "output_path": "/nix/store/pkg-out",
                    "error": None,
                },
            }
        ],
    },
}

LINUX_JSON = {
    "version": 1,
    "metadata": {
        "requested_systems": ["x86_64-linux"],
        "available_systems": [
            "aarch64-darwin",
            "aarch64-linux",
            "x86_64-darwin",
            "x86_64-linux",
        ],
    },
    "changes": {
        "added": [
            {
                "attr_path": "packages.x86_64-linux.new",
                "drv_path": "/nix/store/new.drv",
                "output_type": "packages",
                "system": "x86_64-linux",
                "name": "new",
                "build": {
                    "success": True,
                    "output_path": "/nix/store/new-out",
                    "error": None,
                },
            }
        ],
        "removed": [],
        "modified": [],
    },
}


def _write_json_temp(data: dict) -> str:  # type: ignore[type-arg]
    """Write JSON data to a temp file and return the path."""
    f = tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".json",
        delete=False,
    )
    json.dump(data, f)
    f.close()
    return f.name


def test_merge_json_reports() -> None:
    """Test merging two JSON reports produces unified markdown."""
    darwin_path = _write_json_temp(DARWIN_JSON)
    linux_path = _write_json_temp(LINUX_JSON)

    merged = merge_json_reports(
        [darwin_path, linux_path],
        title="Flake Review Results",
    )

    # Single title
    lines = [line for line in merged.split("\n") if line.startswith("# ")]
    assert len(lines) == 1

    # Content from both reports
    assert "packages.aarch64-darwin.pkg" in merged
    assert "packages.x86_64-linux.new" in merged

    # Nix diff from darwin report
    assert "- old" in merged
    assert "+ new" in merged

    # Combined systems
    assert "aarch64-darwin" in merged
    assert "x86_64-linux" in merged

    # Sections are merged (Added + Modified, not duplicated)
    assert "Added (1)" in merged
    assert "Modified (1)" in merged

    # Single footer
    assert merged.count("Generated by [flake-review]") == 1

    Path(darwin_path).unlink()
    Path(linux_path).unlink()


def test_merge_json_single_report() -> None:
    """Test merging a single JSON report."""
    path = _write_json_temp(LINUX_JSON)

    merged = merge_json_reports([path], title="Test")

    assert "# Test" in merged
    assert "packages.x86_64-linux.new" in merged
    assert merged.count("Generated by [flake-review]") == 1

    Path(path).unlink()
